=== WCRP-CMIP/CMIP6Plus_CVs/JSONLD/source/id/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "CMIP6 Source ID",
    "type": "object",
    "required": [
        "@id",
        "@type",
        "source-id:name",
        "source-id:label",
        "source-id:label_extended",
        "source-id:release_year",
        "source-id:activity_participation",
        "source-id:cohort",
        "source-id:institution_id",
        "source-id:contributers",
        "source-id:license",
        "source-id:model_component"
    ],
    "properties": {
        "@id": {
            "type": "string",
            "format": "uri",
            "pattern": "^cmip6plus:source/id/.+$"
        },
        "@type": {
            "type": "string",
            "pattern": "^cmip:source_id$"
        },
        "source-id:name": {
            "type": "string"
        },
        "source-id:label": {
            "type": "string"
        },
        "source-id:label_extended": {
            "type": "string"
        },
        "source-id:release_year": {
            "type": "integer",
            "minimum": 2000,
            "maximum": 2100
        },
        "source-id:activity_participation": {
            "type": "object",
            "properties": {
                "@set": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri",
                                "pattern": "^cmip6plus:activity/.+$"
                            }
                        },
                        "required": [
                            "@id"
                        ]
                    }
                }
            },
            "required": [
                "@set"
            ],
            "additionalProperties": false
        },
        "source-id:cohort": {
            "type": "string",
            "enum": [
                "published"
            ]
        },
        "source-id:institution_id": {
            "type": "object",
            "properties": {
                "@id": {
                    "type": "string",
                    "format": "uri",
                    "pattern": "^mip-cmor-tables:institutions/.+$"
                }
            },
            "required": [
                "@id"
            ],
            "additionalProperties": false
        },
        "source-id:contributers": {
            "type": "object",
            "properties": {
                "@set": {
                    "type": "object"
                }
            },
            "required": [
                "@set"
            ]
        },
        "source-id:license": {
            "type": "object",
            "properties": {
                "@nest": {
                    "type": "object",
                    "properties": {
                        "license:type": {
                            "type": "object",
                            "properties": {
                                "@id": {
                                    "type": "string",
                                    "format": "uri",
                                    "pattern": "^mip-cmor-tables:license/.+$"
                                }
                            },
                            "required": [
                                "@id"
                            ],
                            "additionalProperties": false
                        },
                        "license:exceptions_contact": {
                            "type": "string"
                        },
                        "license:source_specific_info": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "license:type",
                        "license:exceptions_contact",
                        "license:source_specific_info"
                    ],
                    "additionalProperties": false
                }
            },
            "required": [
                "@nest"
            ],
            "additionalProperties": false
        },
        "source-id:model_component": {
            "type": "object",
            "properties": {
                "@list": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "format": "uri",
                                "pattern": "^cmip6plus:model/component/.+$"
                            }
                        },
                        "required": [
                            "@id"
                        ]
                    }
                }
            },
            "required": [
                "@list"
            ],
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== WCRP-CMIP/CMIP6Plus_CVs/JSONLD/source/id/noresm2-lm.json
{
    "@id": "cmip6plus:source/id/noresm2-lm",
    "@type": "cmip:source_id",
    "source-id:name": "NorESM2-LM",
    "source-id:label": "NorESM2-LM",
    "source-id:label_extended": "NorESM2-LM (low atmosphere-medium ocean resolution, GHG concentration driven)",
    "source-id:release_year": 2017,
    "source-id:activity_participation": {
        "@set": [
            {
                "@id": "cmip6plus:activity/CMIP"
            },
            {
                "@id": "cmip6plus:activity/LESFMIP"
            }
        ]
    },
    "source-id:cohort": "published",
    "source-id:institution_id": {
        "@id": "mip-cmor-tables:institutions/ncc"
    },
    "source-id:contributers": {
        "@set": {}
    },
    "source-id:license": {
        "@nest": {
            "license:type": {
                "@id": "mip-cmor-tables:license/cc-by-4.0"
            },
            "license:exceptions_contact": "@met.no <- noresm-ncc",
            "license:source_specific_info": ""
        }
    },
    "source-id:model_component": {
        "@list": [
            {
                "@id": "cmip6plus:model/componets/osloaero"
            },
            {
                "@id": "cmip6plus:model/componets/cam-oslo"
            },
            {
                "@id": "cmip6plus:model/componets/oslochemsimp"
            },
            {
                "@id": "cmip6plus:model/componets/clm"
            },
            {
                "@id": "cmip6plus:model/componets/cism"
            },
            {
                "@id": "cmip6plus:model/componets/micom"
            },
            {
                "@id": "cmip6plus:model/componets/hamocc"
            },
            {
                "@id": "cmip6plus:model/componets/cice"
            }
        ]
    }
}
